
ERROR:root:Divided by zero error
Traceback (most recent call last):
  File "d:\Documents and Works\Python\Debugging\code2.py", line 6, in <module>
    temp=a/b
ZeroDivisionError: division by zero
ERROR:root:Divided by zero error
Traceback (most recent call last):
  File "d:\Documents and Works\Python\Logging\code2.py", line 6, in <module>
    temp=a/b
ZeroDivisionError: division by zero
